services:
  postgres:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER} # Пользователь постгреса
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} # Пароль для пользователя постгреса
      - POSTGRES_DB=${DATABASE_NAME} # Имя базы данных
    volumes:
      - gameguru-data-db:/var/lib/postgresql/data
    networks:
      - dbnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    restart: always
    networks:
      - dbnet
    expose:
      - 8090
    ports:
      - "90:8090"
    volumes:
      - gameguru-static:/usr/share/nginx/html/static
      - gameguru-uploads:/usr/share/nginx/html/uploads
      - gameguru-logs:/app/www/gameguru/logs
      - ./nginx-global.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
    cpus: "0.50"

  react-builder:
    build: ./frontend
    container_name: react-builder
    networks:
      - dbnet
    volumes:
      - gameguru-static:/app/www/gameguru/client/dist

networks:
  dbnet:
    driver: bridge

volumes:
  gameguru-static:    # Только для React статики
  gameguru-uploads:   # Пользовательские загрузки
  gameguru-data-db:   # Данные БД
  gameguru-logs:      # Для логов
