services:
  postgres:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER} # Пользователь постгреса
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} # Пароль для пользователя постгреса
      - POSTGRES_DB=${DATABASE_NAME} # Имя базы данных
    volumes:
      - gameguru-data-db:/var/lib/postgresql/data
    networks:
      - dbnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # pgAdmin (опционально)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - dbnet
    env_file:
      - .env
    volumes:
      - gameguru-pgadmin-data:/var/lib/pgadmin

  # PHP Backend
  php-backend:
    build: ./backend
    image: gameguru-php-backend:v0.1
    container_name: php-backend
    restart: always
    volumes:
      - .env:/app/www/gameguru/backend/.env
      - gameguru-backend:/app/www/gameguru/backend
      - ./backend/uploads:/app/www/gameguru/backend/uploads
    depends_on:
      - postgres
    networks:
      - dbnet
    env_file:
      - .env
    expose:
      - 9000

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    restart: always
    networks:
      - dbnet
    expose:
      - 8090
    ports:
      - "90:8090"
    volumes:
      - gameguru-static:/usr/share/nginx/html/static
      - gameguru-backend:/app/www/gameguru/backend
      - ./backend/uploads:/usr/share/nginx/html/uploads
      - ./backend/storage/logs/nginx_logs:/app/www/gameguru/backend/storage/logs/nginx_logs
      - ./nginx-global.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - php-backend
      - react-builder
    cpus: "0.50"

  react-builder:
    build: ./frontend
    container_name: react-builder
    networks:
      - dbnet
    volumes:
      - gameguru-static:/app/www/gameguru/client/dist

networks:
  dbnet:
    driver: bridge

volumes:
  gameguru-static:    # Только для React статики
  gameguru-backend:   # Код бэкенда
  gameguru-data-db:   # Данные БД
  gameguru-pgadmin-data: # Данные pgAdmin
